apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-api-provider-kwok.fullname" . }}-aggregated-manager-role
  labels:
    {{- include "cluster-api-provider-kwok.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      kwok.cluster.x-k8s.io/aggregate-to-manager: "true"
rules: []
