{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-api-provider-kwok.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-api-provider-kwok.labels" . | nindent 4 }}
{{- end }}
