package cluster

import (
	"context"
	"fmt"
	"net"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"time"

	"github.com/pkg/errors"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/utils/ptr"
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/client-go/tools/clientcmd/api"
	clusterv1 "sigs.k8s.io/cluster-api/api/core/v1beta2"
	"sigs.k8s.io/cluster-api/util/kubeconfig"
	"sigs.k8s.io/cluster-api/util/record"
	"sigs.k8s.io/cluster-api/util/secret"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/kwok/pkg/config"
	kwokruntime "sigs.k8s.io/kwok/pkg/kwokctl/runtime"
)

func (s *Service) Reconcile(ctx context.Context) (ctrl.Result, error) {
	logger := s.scope.Logger
	logger.Info("Reconciling KwokControlPlane")

	kwokctlConfiguration := config.GetKwokctlConfiguration(ctx)
	kwokctlConfiguration.Options.Runtime = s.scope.Runtime()

	buildRuntime, ok := s.runtimeProvider.Get(s.scope.Runtime())
	if !ok {
		return ctrl.Result{}, fmt.Errorf("runtime %q not found", s.scope.Runtime())
	}
	rt, err := buildRuntime(s.scope.Name(), s.scope.WorkDir())
	if err != nil {
		return ctrl.Result{}, fmt.Errorf("runtime %v not available: %w", s.scope.Runtime(), err)
	}

	_, err = rt.Config(ctx)
	if err == nil {
		// Cluster already exists — check if ready
		logger.Info("Cluster already exists")
		ready, readyErr := rt.Ready(ctx)
		if readyErr != nil {
			logger.Info("Cluster not ready yet, will retry", "error", readyErr)
			return ctrl.Result{RequeueAfter: 5 * time.Second}, nil
		}
		if ready {
			logger.Info("Cluster is already ready")
			s.scope.ControlPlane.Status.Ready = true
			s.scope.ControlPlane.Status.Initialized = true
			s.scope.ControlPlane.Status.Initialization.ControlPlaneInitialized = ptr.To(true)

			if err := s.reconcileKubeconfig(ctx, rt); err != nil {
				return ctrl.Result{}, fmt.Errorf("reconciling kubeconfig: %w", err)
			}

			return ctrl.Result{}, nil
		}
		// Exists but not ready — try starting and requeue
		logger.Info("Cluster exists but not ready, starting")
		if startErr := rt.Up(ctx); startErr != nil {
			logger.Info("Failed to start cluster, will retry", "error", startErr)
		}
		return ctrl.Result{RequeueAfter: 5 * time.Second}, nil
	}

	// First-time creation
	start := time.Now()
	logger.Info("Cluster is creating")

	err = rt.SetConfig(ctx, kwokctlConfiguration)
	if err != nil {
		logger.Error(err, "Failed to set config")
		return ctrl.Result{}, err
	}
	err = rt.Save(ctx)
	if err != nil {
		logger.Error(err, "Failed to save config", err)
		return ctrl.Result{}, err
	}

	err = rt.Install(ctx)
	if err != nil {
		logger.Error(err, "Failed to setup config")
		return ctrl.Result{}, err
	}
	logger.Info("Cluster is created",
		"elapsed", time.Since(start),
	)

	if err := s.reconcileKubeconfig(ctx, rt); err != nil {
		return ctrl.Result{}, fmt.Errorf("reconciling kubeconfig: %w", err)
	}

	start = time.Now()
	logger.Info("Cluster is starting")
	err = rt.Up(ctx)
	if err != nil {
		return ctrl.Result{}, fmt.Errorf("failed to start cluster %q: %w", s.scope.Name(), err)
	}
	logger.Info("Cluster is started",
		"elapsed", time.Since(start),
	)

	// Requeue to verify readiness
	return ctrl.Result{RequeueAfter: 5 * time.Second}, nil
}

func (s *Service) reconcileKubeconfig(ctx context.Context, rt kwokruntime.Runtime) error {
	logger := s.scope.Logger

	logger.Info("Reconciling kubeconfig for cluster", "cluster", s.scope.Name())

	clusterRef := types.NamespacedName{
		Name:      s.scope.Cluster.Name,
		Namespace: s.scope.Cluster.Namespace,
	}

	configSecret, err := secret.GetFromNamespacedName(ctx, s.scope.Client, clusterRef, secret.Kubeconfig)
	if err != nil {
		if !apierrors.IsNotFound(err) {
			return errors.Wrap(err, "failed to get kubeconfig secret")
		}

		if createErr := s.createKubeconfigSecret(ctx, &clusterRef, rt); createErr != nil {
			return fmt.Errorf("creating kubeconfig secret: %w", createErr)
		}
	} else {
		logger.V(2).Info("kubeconfig secret already exists", "name", configSecret.Name, "namespace", configSecret.Namespace)
	}

	return nil
}

func (s *Service) createKubeconfigSecret(ctx context.Context, clusterRef *types.NamespacedName, rt kwokruntime.Runtime) error {
	controllerOwnerRef := *metav1.NewControllerRef(s.scope.ControlPlane, s.scope.ControlPlane.GroupVersionKind())

	clusterName := s.scope.Name()
	userName := fmt.Sprintf("%s-capf-admin", clusterName)
	contextName := fmt.Sprintf("%s@%s", userName, clusterName)

	// Read the kubeconfig generated by kwok's Install step. This has the
	// correct server URL (https when SecurePort=true) and cert file paths.
	kwokKubeconfigPath := filepath.Join(s.scope.WorkDir(), kwokruntime.InHostKubeconfigName)
	kwokCfg, err := clientcmd.LoadFromFile(kwokKubeconfigPath)
	if err != nil {
		return fmt.Errorf("loading kwok kubeconfig from %s: %w", kwokKubeconfigPath, err)
	}

	// Extract server URL from the kwok kubeconfig, replacing the bind
	// address with the cluster's external address.
	serverURL := ""
	for _, c := range kwokCfg.Clusters {
		serverURL = c.Server
		break
	}
	if serverURL == "" {
		return fmt.Errorf("kwok kubeconfig has no cluster entry")
	}

	// Replace loopback address with pod IP so CAPI (in another pod) can reach
	// the kwok API server.
	if podIP := os.Getenv("POD_IP"); podIP != "" {
		parsed, err := url.Parse(serverURL)
		if err == nil && (parsed.Hostname() == "127.0.0.1" || parsed.Hostname() == "localhost") {
			parsed.Host = net.JoinHostPort(podIP, parsed.Port())
			serverURL = parsed.String()
		}
	}

	// Set ControlPlaneEndpoint so the CAPI Cluster object gets the correct endpoint.
	if parsed, err := url.Parse(serverURL); err == nil {
		port, _ := strconv.Atoi(parsed.Port())
		s.scope.ControlPlane.Spec.ControlPlaneEndpoint = clusterv1.APIEndpoint{
			Host: parsed.Hostname(),
			Port: int32(port),
		}
	}

	cluster := &api.Cluster{
		Server: serverURL,
	}
	user := &api.AuthInfo{}

	// Embed TLS cert data if PKI files exist (SecurePort=true).
	pkiPath := filepath.Join(s.scope.WorkDir(), kwokruntime.PkiName)
	if caCert, err := os.ReadFile(filepath.Join(pkiPath, "ca.crt")); err == nil {
		cluster.CertificateAuthorityData = caCert
	}
	if clientCert, err := os.ReadFile(filepath.Join(pkiPath, "admin.crt")); err == nil {
		user.ClientCertificateData = clientCert
	}
	if clientKey, err := os.ReadFile(filepath.Join(pkiPath, "admin.key")); err == nil {
		user.ClientKeyData = clientKey
	}

	cfg := &api.Config{
		APIVersion: api.SchemeGroupVersion.Version,
		Clusters:   map[string]*api.Cluster{clusterName: cluster},
		Contexts: map[string]*api.Context{
			contextName: {
				Cluster:  clusterName,
				AuthInfo: userName,
			},
		},
		AuthInfos:      map[string]*api.AuthInfo{userName: user},
		CurrentContext: contextName,
	}

	out, err := clientcmd.Write(*cfg)
	if err != nil {
		return errors.Wrap(err, "failed to serialize config to yaml")
	}

	kubeconfigSecret := kubeconfig.GenerateSecretWithOwner(*clusterRef, out, controllerOwnerRef)
	if err := s.scope.Client.Create(ctx, kubeconfigSecret); err != nil {
		return errors.Wrap(err, "failed to create kubeconfig secret")
	}

	record.Eventf(s.scope.ControlPlane, "SucessfulCreateKubeconfig", "Created kubeconfig for cluster %q", s.scope.Name())
	return nil
}
