image:
  repository: docker.io/sebest/cluster-api-provider-kwok
  tag: dev
  pullPolicy: Always

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi

leaderElect: true
metricsBindAddr: "localhost:8080"
healthAddr: ":9440"

# Docker socket path on the host. Required for the kind and docker runtimes
# to create sibling clusters via the host Docker daemon.
dockerSocket:
  hostPath: /var/run/docker.sock

serviceAccount:
  create: true
  name: ""

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
